---
apiVersion: v1
kind: Namespace
metadata:
  name: authentication
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: authentication
  labels:
    app: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: danluck001/node-auth
        ports:
        - name: http
          containerPort: 3001
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: authentication
spec:
  selector:
    app: auth-api
  ports:
  - protocol: TCP
    port: 3001